[package]
name = "textdm"
version = "0.1.0"
authors = ["Jonathan Krebs <jonathan.krebs@bruckbu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam-client = "*"
nix = "0.20"
libc = "*"
rust-ini = "*"
pwd = "*"
